### ISSUE TITLE
App: 'Web page not available' when app runs in background/phone closed for a while.

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1086]
Reproduce:
1. Open customer K app
2. Close your phone and put it away for 10 minutes
3. Open your phone. Android will show the following page. iOS shows an error dialog.
![image](https://github.com/openremote/openremote/assets/14177035/26065118-a4fe-40af-85bb-d844b1e454f5)

Expected:
3. Open your phone. The app continues as it was.

Is this resolved with an offline token?

**Comment by MartinaeyNL** [comment]
Put a fix in place in PR #1089.

Basically what was happening was:
When running the app in the background, and opening it again, it would prompt a login screen since the token was expired.

With this PR, it does a check beforehand whether keycloak is accessible, to make sure the user can
safely redirect to that login page. (preventing a "no internet available" error from appearing)
If that is not the case, it will fallback to the default mechanism of requesting a token every 30 seconds.
So, when launching the app, it takes around 30 seconds to show all data correctly.

This is where we should take next steps.
- Maybe lower the interval during a disconnect, similar to websocket?
- To prevent incorrect data being shown, show a "No internet connection" placeholder page instead?
(as @richturner mentioned in calls earlier)

**Comment by MartinaeyNL** [comment]
Correction: it requests the token every 10 seconds. Don't think it's necessary to lower that interval even more.
