### ISSUE TITLE
JSON Object

### ISSUE THREAD

**Issue by jcheca** [openremote/openremote#1175]
In the latest docker image of the manager (3a31b8f4cca4) I cannot see the content of a JSON object added to an asset to retrieve the information of an HTTPLink agent, it does not show it in the field defined for this purpose as the previous image did (ff1c7342ee00); I don't know if this is the case in the new version, because it actually recovers the data so it can be used with an AttributeLink but it doesn't show anything in the attribute used to retrieve the request information.

**Comment by PepijnMuskens** [comment]
The latest update had a lot of changes to the validation for assets but it seems like the attribute input field of the type "JSON object" does not validate the data correctly. If you want to see the data in the field which gets the data you could change the value type of the attribute to "JSON" instead of "JSON object", this one should have a working validation in your image.

**Comment by PepijnMuskens** [comment]
Reproduce:
1. add an attribute to any asset with the value type "JSON object".
2. fill in a valid Json in the value field of the new attribute (e.g.: `{"test":true}`).
3. save the asset.

The asset is now saved with the json value in the new attribute but when viewing the asset the value is not loaded in the input field.

expected behaviour: 
The value is shown in the input field when saving data.
