### ISSUE TITLE
Alarms: additional information on source of alarm (rule ID, username)

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1312]
The source of an alarm should contain the rule ID or username if created by When-Then rule or manually respectively.

- [ ] If alarm is created by a when-then rules, add the rule id to the source field. E.g. "Rules (ID: 1234)"
- [ ] If alarm is created manually, add the username of the creator to the source field. E.g. "Manual (donwillems)"

**Comment by wborn** [comment]
It will now set the alarm `sourceId` to the `ruleId` or the `userId` in the database depending on if the alarm was created by a rule or manually. I opted for the userId instead of the username because the `assigneeId` is also based on a `userId`. It doesn't show this info in the manager UI yet but it should be easy to add.

**Comment by wborn** [comment]
With the latest commit it will now also show the source rule ID or username in the UI.
