### ISSUE TITLE
Update a-e project to latest submodule and recreate instance

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1316]

**Comment by MartinaeyNL** [comment]
Status: progress is good until now.

@DonWillems asked me to take a look at some errors.
These are in regards to the Redux store, apparently not being defined upon the `constructor()` of the page.
When I took a quick look at the codebase, nothing seemed off. (compared to other custom projects)
I'll take a look to identify to debug what is going on;

![image](https://github.com/openremote/openremote/assets/27913110/4a6e3675-b0dc-469d-b462-a75caf21ade4)

**Comment by MartinaeyNL** [comment]
Found the issue;

With all our (custom) apps, we register pages in functions like `pageAssetsProvider()`, and `pageMapProvider()`.
The pages are normally loaded on the top level, sharing a Redux store through `or-app`.

However, in this custom app, the page is loaded within a child component.
And since it's initialized using a HTML tag, it cannot properly create a Redux store using `or-app`.

Luckily, the Redux store is not used within this custom app, so no issues should appear.

Code snippet of the `*******-view.ts` component;
```
  protected render(): TemplateResult | void {
    const items = this.items.map(item => {
      if(item.name == "status") {
        item.content = html`<page-assets .assets="${this.assets}" .assetId="${this.assetId}"></page-assets>`
      }
      else if(item.name == "location") {
        item.content = html`<page-map .assets="${this.assets}" .assetId="${this.assetId}"></page-map>`
      }
      else if(item.name == "support") {
        item.content = html`<page-support></page-support>`
      }
      return item;
    })
 ```
