### ISSUE TITLE
Create (and edit) asset

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#138]
- [x] dropdown '+' for 'Asset' in asset list
- [ ] modal for asset with list to select type (see designs)
- [ ] also reached when selecting edit mode 
- [ ] Replicate all GWT asset / edit mode functionality

**Asset:** 
- Only option to create attributes that are either filled in through interface, rule, replay or attribute link with connection agent.
- Set label, description and unit type (set in agent?)
- Set configuration items, redesign

How to set attribute value type? If set, does that filter the list of available assets to link to, or does it come with the linked attribute and you dont set it here.

Asset types to be present t.b.d.:
- [x] Light
- [x] Environment
- [x] Thermostat
- [x] People Counter
- [x] Sound
- [x] Microphone
- [ ] Survey
- [x] Electricity Producer
- [x] Electricity Consumer
- [ ] ?????

**Comment by DonWillems** [comment]
Copy from group issue, clean up later:

Designs for the issue and additional info per checkbox.

Image 1: Add asset and group children attribute panel
![Manager_Assets- panel data table](https://user-images.githubusercontent.com/14177035/78132454-0d0c3980-741d-11ea-8e13-b5302758f00e.png)
Image 2: Add asset modal showing all available asset types. Only further define group for now.
![Manager_Assets- panel data table copy 2](https://user-images.githubusercontent.com/14177035/78130782-3aa3b380-741a-11ea-8366-7ae963488da5.png)
Image 3: Add/remove attributes (columns) for the children panel.
![Manager_Assets- panel data table copy](https://user-images.githubusercontent.com/14177035/78130784-3b3c4a00-741a-11ea-9718-f43f24b3359a.png)

- [ ] dropdown '+' for 'Add asset' in asset list
_Similar to 'sort' in the asset list header as example_ 
- [ ] modal for group to set name and parent
_For modal help see or-chart, or-header language select, and https://material.io/components/dialogs/#usage_
- For parent selection in modal, use asset list to pick asset. Can we make this appear as a drop down list? By default the current position in the asset list should be used. As if adding the group at the same level of the selected asset.
- After adding the group, go to this asset page. Later it will have to go to the asset page in edit mode.
- Note: assetTypes need a description. Discuss implementation
- [ ] Make assetType icon and icon color over-writable by attribute (or other better approach)
_**SKIP FOR NOW**_
- [ ] Make the assetType group. The group asset page should only have: info and children panels. Later we can enable chart too.
- [ ] Overview child assets panel. Panel or-child-attributes (or a name that makes the most sense). Shows all children, later can add an option to modify asset list. Configure columns by selecting available attributes. Sortable per column.
_For data table help see or-history panel, in the case of events/objects_

- At the moment the parent of assets cannot be chosen through the UI, so creating an actual group with assets can not be done through this interface. Use the GWT manager for this.
- Between assetTypes it can be that attributes with the same name have different labels, choose the easiest option to show one of the labels.
- For now, give all columns same space. This could make all columns unreadable if too many are chosen. So no horizontal scroll.
- Values in columns that overflow should have ellipses
- On hover show full value of cell (as title tag)
- Clicking on a top cell (header) sorts it, clicking again sorts or the other way around. By default it is sorted based on the first column. Direction is shown by arrows.
- Max height of the data table is 500px, for taller tables, make header sticky and the rows scrollable.
- Attributes can be chosen as shown in image 3. Add possibility for checkboxes to list in modal.
- Add attribute modal (image 3) lists all attributes found on the children of the group asset, filtered by the asset viewer config for those asset types and deduplicated.

- [ ] Give the panel a config so that it can be predefined what is shown by default.
_For config help see page-assets, history panel and attribute panel asset type attribute exclusion_

- [ ] Implement generic panel options


Don't forget translation for attribute labels, modals and panel header.

**Comment by DonWillems** [comment]
Edit asset page proposal.

All attributes should be prepared in agents, rules, replay or can be written through the UI.
Here an example of sound level linked to an attribute of an agent.

![Manager Edit agent asset-06](https://user-images.githubusercontent.com/14177035/78509824-36b4c000-7791-11ea-96a4-b3cdb0a448ee.png)
