### ISSUE TITLE
Notifications: Browser does not open when opening push notification

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1467]
**Reproduce:**
1. Create When-Then rule with push notification action. Set e.g. "openremote.io" as URL and enable "open in external browser"
2. Trigger the rule
3. Receive push notification
4. Open the push notification by clicking it or by pressing the action button
5. Nothing happens
6. Do this a few more times and on Android you get the warning "[App name] keeps closing"

**Expected:**
5. Website opens in default browser

This is an issue in both Android and iOS

Tested on Android 13

**Comment by Miggets7** [comment]
I've noticed that when creating a rule, `openInBrowser` appears to be on, but the notification sent has it set to `false`. Only after turning the toggle off, saving, turning it back on and saving it, makes the notification to have `openInBrowser` set to `true`.

Seems like some UI bug

Also, it's important to have `http(s)://` in the url, otherwise the app can't determine what activity should be opened.

I could though, add some code that checks if `openInBrowser` is set to `true`, to then check if `https://` should be appended.

@DonWillems should I add that?

**Comment by Miggets7** [comment]
I've checked the code in `or-rule-form-push-notification.ts` and it hasn't been modified for over 4 years, so not sure why it's broken now. Maybe something for @MartinaeyNL to check?
