### ISSUE TITLE
Users: show password policy on user page

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1518]
Currently if a password policy is set on a realm it is not shown on the users page, making it confusing to the admin why a password they are setting is not accepted.

- Add the password policy set below the password fields.
- Make sure translations are in, these can be borrowed from Keycloak: https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/admin/messages/messages_en.properties

![Image](https://github.com/user-attachments/assets/efa5e125-a68b-4478-bbd0-a607a9e424e2)

**Comment by MartinaeyNL** [comment]
Started working on this. Will investigate what is necessary to implement this.

**Comment by MartinaeyNL** [comment]
Remarks on the scope of the issue:

During implementation we came across the following issue;
"When saving (or updating) a user with an invalid password, it still updates the user"

This is because you cannot predefine a password during user creation in Keycloak.
We 'hack' this, by requesting a password reset directly after the 'save' button is pressed. This changes the password correctly.
Generally this is a bad practice, so we should get rid of this in the future.
The scope here is to add the password policy on the users page.

Because of that, we cannot "block user creation" when a bad password is given.
Me and @DonWillems concluded, as a short term solution, to simply show a "save password failed" snackbar afterwards.
