### ISSUE TITLE
Service to support push notifications in manager

### ISSUE THREAD

**Issue by ebariaux** [openremote/openremote#20]
Push notifications use Google FCM as delivery mechanism.
Have a resource for console to register to potentially receive notifications (id, token).
This information is linked to a user (stored as user attribute in Keycloak)

Have a service for manager to send notifications to all devices registered for a user.

**Comment by christianbauer** [comment]
What happens when several users log in through the same mobile device?

The Android notification needs an icon.

We currently use transient facts (AlarmTrigger, UserNotified) to handle the alarm condition in rules, so this might cause funny behaviour when the server is restarted and state is lost. What are those problems, it should be fine to send another notification within the interval time window, even if it's only been 10 minutes instead of 30 since the last notification.

The notification should contain the server time when the notification was triggered, this can be shown on notifications on the app (e.g. "Alarm triggered at 03:30 today.").

**Comment by pierrekil** [comment]
Push notification should display in front (on Android). It now just displays when pulling down notifications list from the top.

The favicon displays within a circle, while it should display as a direct image without the circle.

**Comment by ebariaux** [comment]
See #52 for follow-up
