### ISSUE TITLE
Rule scheduler

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#277]
- [x] 'Every day on Monday, Tuesday', should be 'Every Monday, Tuesday
- [x] Label not always immediately updated when schedule is saved in modal. Only gets updated when Rule is Saved.
- [x] setting 'repeating occurrence'. Change the day, than month, than year, shows strange behavior. Same as #334

**Comment by robin-dekkers** [comment]
1. It is not easy to change to name for 'Every day on'. This text is generated by the library rrule.js and the text cannot be changed because it is auto generated. To make this possible significant changes need to be made in which we write this functionality ourselves.

2. Is hard to reproduce, I tried multiple methods to change te settings but could not reproduce. Do you have more information how to reproduce the problem?

**Comment by pierrekil** [comment]
Both above are fine to leave as is, please also try setting 'repeating occurrence'. Change the day, than month, than year, shows strange behavior.
Please walk through all options and see whether you see any additional bugs.
