### ISSUE TITLE
Update Keycloak for ARM64 (new Macbook)

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#348]

**Comment by Miggets7** [comment]
It's seems the templating in the themes has changed in V12 of Keycloak. See the attached files

@aktur is it possible to use V11 in the multi.Dockerfile?

Otherwise we need to go through all the templates.

[V11_template_login.txt](https://github.com/openremote/openremote/files/6068140/V11_template_login.txt)
[V12_template_login.txt](https://github.com/openremote/openremote/files/6068141/V12_template_login.txt)

**Comment by aktur** [comment]
Unfortunately V11 is already archived and set on non active. This means that it is not easy to recreate a tool-flow. I was trying to recreate V11 build from tar archive, but after spending about one hour without success I've decided that it is probably better to update to supported version anyway. Problems with 11.0.2 (version which we are using currently) is that it does not even exists in the git log (this is probably a side effect of rebasing), therefore I cannot even recreate what was the source code they've used to make this image. Anyway, we have to spend time here if we want to go on. IMHO is better to go to V12 instead of trying to recreate V11.

**Comment by aktur** [comment]
Falling back on a default template instead of 500 would be better for MVP. Currently there is no working solution for arm64. Basic authentication results in blank manager page and Keycloak V12 results in server error.

**Comment by richturner** [comment]
The `keycloak` doesn't support fallbacks for themes, if a theme is specified for a realm it expects that directory to exist and to contain a valid theme.

**Comment by richturner** [comment]
We should indeed move to `v12` considering this is our authentication layer, being out of date is not a good thing.

**Comment by aktur** [comment]
I'm not sure how keycloak is working, but what I've noticed is that when calling keycloak:multi image without manager (e.g. docker run -ti openremote/keycloak:multi) then it doesn't crash and gives some default templates. So my idea was, that crashing it is caused by the manager, therefore if the manager sees 500s from keycloak it can simply stop asking for actions that causes it. I think this was behaviour before, but I can be wrong of course.

**Comment by richturner** [comment]
The manager modifies the theme for the master realm to be `openremote` this doesn't exist in stock `keycloak` so you get the 500 error which appears as `NullPointerException` in `keycloak` logs. You'll see that the old `keycloak` `Dockerfile` has a custom entry point which I put in place to symlink the custom themes into the `keycloak` themes dir.

Not possible to alter the themes directory location in keycloak (although I want to look at the ThemesResourceProvider SPI to see if we can use that somehow).
