### ISSUE TITLE
Custom attributes do not appear in rule selector

### ISSUE THREAD

**Issue by alvarheras** [openremote/openremote#423]
Hi all, 

I have been working with openremote for a short time, my congratulations to the developers.

When I want to apply a "When" "Then" rule on a custom asset like a building it doesn't get the attributes to show them in the selector.

![cddcdcdcdcdcd](https://user-images.githubusercontent.com/78783994/119118218-4b522700-ba2a-11eb-934a-0f68f6614c9c.PNG)

It only happens when a custom asset is selected.

Throws a console error of this type. 

![errror](https://user-images.githubusercontent.com/78783994/119118527-93714980-ba2a-11eb-94d7-c88a4cf19679.PNG)

Could it be due to some kind of error with package versions?

I hope your help, if you need more information tell me.

Thx

**Comment by pierrekil** [comment]
Hi, you should add a configuration item to the attribute, called 'Rules state' and activate that. You can do that by selecting the  'Casa' asset, turn on 'edit asset' and uncollapse the attribute you want to be available for the rules. Otherwise only attributes which are filled by agents are available for rules.

**Comment by alvarheras** [comment]
Perfect, your solution was provided to me. Next time I will comment on the forum. Thank you .
