### ISSUE TITLE
Users: a username with a capital letter or space is not be saved

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#424]
Add hint text that says "Only number and lower case letters allowed"
Add validation that shows the field is incorrect.

**Comment by pierrekil** [comment]
Capital letter get's automatically changed into small -> OK
When saving name with space, modal closes and no user created, without any warning.

Expected: don't accept saving for 2nd and give an error message

**Comment by richturner** [comment]
User page has been fixed by commit 3a83f69378d49f4830ea162076b669ee304e51ef

Seems that keycloak's own user registration page allows spaces in usernames (even leading spaces) which is a bit strange, we should look to update the registration template to prevent this as we cannot catch that in our system.
