### ISSUE TITLE
Improvements asset workflow

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#43]
- [ ] Populate attribute types when asset type is selected (e.g. agent -> protocol config attributes)
- [x] Make Thing the default asset type
- [x] Thing should not be a leaf so child assets can be added
- [ ] Default values for protocol configuration meta items (e.g. KNX host -> IP address), however breaks validation flow?
- [x] Discovery/import should only be possible when protocol configuration attribute edit is complete (protocol status indicator)
- [ ] Naming convention for KNX/ETS import: group addresses should map to multiple attributes on a single asset, not multiple assets
- [x] Attribute link doesn't populate asset list dropdown
- [x] Detect loops when processing attribute link messages (maybe by detecting source of AttributeEvent)

**Comment by richturner** [comment]
1.  Is trickier than first thought because we have the concept of agent connectors that are used to resolve available protocols (will need to think about it some more).
4. As meta items are just strings then any default value will be difficult to validate (as there is no regex option as host names are allowed as well as IP addresses)
6. Would need to enhance the KNX protocol import

**Comment by richturner** [comment]
Implemented Linked Attribute loop detection by not allowing the AttributeLinkingService to generate attribute events when the incoming event was generated by itself...there will be cases where this will prevent legitimate links from being executed so need to look at this in more detail.
