### ISSUE TITLE
Remove 'account' in menu for 'smartcity' user

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#499]

**Comment by richturner** [comment]
This might have come about due to changes in how Keycloak works but now Keycloak creates a composite role called `default-roles-{realm}` for each realm and by default this assigns the `manage-account` role to the `account` client.

Put a method in place to remove the `manage-account` role from the default roles but this should be re-visited when migrating to Keycloak groups.

**Comment by richturner** [comment]
See #502
