### ISSUE TITLE
UI Scaling: Asset page improvements

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#773]
Starting from 5000 assets, the loading of the Asset page for a given asset is taking seconds. We need to take a look on the reason of this timing (select induce too many computing on frontend code, parsing too many data,...)

Another issue appear with such high amount of asset : in View mode, we cannot succeed to write new data value for attribute. The issue doesn't occur on Edit mode.

**Comment by jvervier** [comment]
When selecting an asset in the asset tree, we've got three time consuming elements :  
1. time consumption between or-asset-tree:_onNodeClicked and ...
2. inside or-mwc-input for SELET type, the `this.shadowRoot!.getElementById("mdc-select-menu")!.style.width=component.getBoundingClientRect().width+"px";` command is taking long time (it's there to set the width of the possible select element on the same than the input itself)
3. map generation is the lastest one but, on that moment, we already can see attribute list and value. So this is less impacting the performance.

**Comment by jvervier** [comment]
Hi,
In my research I found a time consuming step on Websocket side. When clicking on an asset in the asset tree, there is message exchante on WS linked to some event, and between a Subscribe and Subscribed, it looks like there is around 1 and 2 secondes depending on the asset (see screen shots from network console on the browser side).

<img width="1851" alt="Screenshot 2022-09-19 at 09 20 43" src="https://user-images.githubusercontent.com/10142800/190968144-cb73a3ed-3387-420e-bf9d-66359e1bf299.png">

**Comment by jvervier** [comment]
After some research, it seems the delay come after the call on org.openremote.manager.event.ClientEventService#sendToSession.

**Comment by jvervier** [comment]
From my tests, time consumption is after the camel processing of sending back from the backend on the WS the message.

Do not know why, for the moment, there is a delay between the processing of the exchange by the backend and the concrete reception on the frontend side. Maybe too much listening on the broker?

**Comment by jvervier** [comment]
Hello @DonWillems, @richturner ,

I notice we're getting the asset info (attributes,...) about the asset we select in the asset tree with the response of the REQUESTRESPONSE message.

For a reason I do not know, there is a long time between the emit of the message from the backend and the reception on frontend level.

Should we consider to load asset data with an assetquery on the API and use only the websocket for event subscricption? As the asset could have a lot of data, I do not know if it could explain de latency I noticed.

If we collect the data to show asset info in the asset page with the API, we could split those two elements and ensure a quick reaction on frontend side and keep WS only for event sync.

**Comment by jvervier** [comment]
ALso need to take a look on the TRIGGERED: message emit on the WS by the backend and their impact on frontend

**Comment by jvervier** [comment]
Other finding (and why I didn't had that idea before!). I do not have the same response time to load asset page between chrome and other browsers (Firefox and Safari).
On Firefox and Safari I've got a quick reaction time, on Chrome I've got more delay.

**Comment by jvervier** [comment]
This issue is not complete :-/

Improvement has been done on asset tree to improve the load/construction time. But We're still having an issue with Chrome based browser where the "Recalculating  style" is longer.

Asset-view is rendered two times when we select an asset in the tree :  
1. As soon after the click on the asset, and it's showing "Loading..." first as we do not have the asset loaded
2. As soon as the asset is get from the backend through the Websocket RequestReponse message.

Asset-view is not destroyed/reconstructed between those two. It's re-rendered has event generate an update of the state of the component.

In both step, the browser is busy to "Recalculating style" (passing through DOM and styling) and it's taking more time on Chrome than other browser. The reason seems to be a different behaviour between the browser.

The page is having more than 5000 <li> object in it. So the page start to have a lot of nodes. Reaction time is really improve if we have an asset tree with only root level of the assets.

@DonWillems Could I've different proposal to make on the asset tree we can discuss today.
